### ISSUE TITLE
Execution error due to hhblits

### ISSUE THREAD

**Issue by jas-preet** [kad-ecoli/hhsuite2#2]
Hi,
when I run 
`python build_MSA.py 5LOS_A.fasta -hhblitsdb= uniclust30_2020_02/UniRef30_2020_02 -jackhmmerdb=UniRef/uniref100.fasta -hmmsearchdb=metaclust/metaclust_nr_2018_01.fasta -tmpdir=temp_files/ -outdir=deepmsa/ -ncpu=20`
I am getting this error at :
`/hhsuite2/bin/hhblits -i temp_files/seq.fasta -diff inf -d /uniclust30_2020_02/UniRef30_2020_02 -cpu 20 -oa3m temp_files/hhblits.a3m  -id 99 -cov 50 -o temp_files/hhblits.log -n 3 -diff inf; grep -v '^>' temp_files/hhblits.a3m|sed 's/[a-z]//g' > temp_files/hhblits.aln
hhlib= /programs/hhsuite2
Error in /programs/hhsuite2/bin/hhblits: could not open file 'uniclust30_2020_02/UniRef30_2020_02.cs219'
`
while when I run everything same on hhsuite3 installed on my machine this works with same dataset. also the cs219 file in my db is `UniRef30_2020_02_cs219.ffdata`
And if I change the path to the hhblits3 it causes problem at a later.

Thanks in advance

**Comment by kad-ecoli** [comment]
hhblits2 does not natively support uniclust30 2019_11 or later. There are three solutions.
1. Use uniclust 2018_08.
2. Use ``scripts/hhblitsdb3to2.py`` to convert the the uniclust30 2019_11 or later from hhblits3 to hhblits2 format. Unfortunately, it is not always possible to perfectly convert the formatm as explained at the top of ``scripts/hhblitsdb3to2.py``.
3. Modify the code to use hhblits3 in the first step where you encounter the error, and use hhblits2 for other steps. This is likely the safest approach. Please note that you will need the hhblits3 3.3.0 or later (or the most recent hhblits), due to a bug in premerge in older version, as explained in https://github.com/soedinglab/hh-suite/issues/205.

By the way, why do you use ``-jackhmmerdb=UniRef/uniref100.fasta`` instead of uniref90.fasta as recommended in our document? Did you benchmark and find it generate more accurate alignment for your purpose? In our benchmark, uniref100.fasta results in more sequences in the MSA but no apparent improvement in subsequent contact prediction.

**Comment by jas-preet** [comment]
Hi,
Thanks for getting back. Using older version of uniclust certainly helps. There was no reason for using of uniref100.fasta in particular except for the reason I already had it downloaded and was using it for dirty testing, I haven't tested if it performs better.
